config/routes.rb
Rails.application.routes.draw do

  resources :sources
  resources :articles

  namespace :api, defaults: { format: 'json' } do
    get 'sources' => 'sources#index'
    get 'items' => 'items#index'
    get 'feeds' => 'feeds#index'
    get 'totals' => 'totals#index'
    get 'pf' => 'totals#photo_finish'
    get 'wordcount' => 'totals#word_count'
    get 'stats' => 'stats#index'
    get 'places' => 'places#index'
  end

  get 'articles/duplicates' => 'articles#show'

  root 'sources#index'

end

app/models/source.rb
class Source < ActiveRecord::Base
	#after_save :fetch_articles

	has_many :feeds, dependent: :destroy
	has_many :articles, through: :feeds
	accepts_nested_attributes_for :feeds, allow_destroy: true
	validates :name, :url, presence: true, uniqueness: true
	validates :acronym, uniqueness: true
	validates :source_type, presence: true 

	# def get_unique_days
	# 	self.articles.pluck(:pub_date).map { |date|
	# 			date.strftime('%Y-%m-%d')
	# 	}.uniq.sort
	# end

	# def get_article_count_by(time_period)
	# 	time_and_totals = []
	# 	if time_period == 'day'
	# 		days = self.get_unique_days
	# 		days.each do |day|
	# 			count = self.articles.where("pub_date BETWEEN ? AND ?", 
	# 				day.to_datetime, day.to_datetime + 1).count
	# 			time_and_totals << [day, count]
	# 		end
	# 	end
	# 	if time_period == 'month'
	# 		(1..12).to_a.each do |month|
	# 			count = self.articles.where("extract(month from pub_date) = ?", month).count
	# 			time_and_totals << [month, count]
	# 		end
	# 	end
	# 	if time_period == 'hour'
	# 		(0..23).to_a.each do |hour|
	# 			count = self.articles.where("extract(hour from pub_date) = ?", hour).count
	# 			time_and_totals << [hour, count]
	# 		end
	# 	end
	# 	time_and_totals
	# end

	def self.all_sources_data
		total_feeds = Feed.count
		articles = Article.all
		total_items = articles.count
		twitter_shares = articles.map(&:twitter_shares).sum
		facebook_shares = articles.map(&:facebook_shares).sum
		total_shares = twitter_shares + facebook_shares
		#total_shares = articles.get_count_by('day').map { |h| h[:total_shares]}.sum
		#twitter_shares = articles.get_count_by('day').map { |h| h[:twitter_shares]}.sum
		avg_twitter_shares = (twitter_shares / total_items.to_f).round(2)
		#facebook_shares = articles.get_count_by('day').map { |h| h[:facebook_shares]}.sum
		avg_facebook_shares = (facebook_shares / total_items.to_f).round(2)
		avg_shares = (total_shares / total_items.to_f).round(2)
		avg_day = articles.average_articles_by('day')
		avg_month = articles.average_articles_by('month')
		sources = Source.all
		categories = articles.category_list
		data = Hash[
						name: 'All',
						total_feeds: total_feeds,
						total_items: total_items,
						total_shares: total_shares,
						twitter_shares: twitter_shares,
						avg_twitter_shares: avg_twitter_shares,
						facebook_shares: facebook_shares,
						avg_facebook_shares: avg_facebook_shares,
						avg_shares: avg_shares,
						avg_day: avg_day,
						avg_month: avg_month,
						sources: sources,
						categories: categories	
					]
		data_array = []
		data_array << data
	end

end

app/controllers/api/sources_controller.rb
module Api
	class SourcesController < ApplicationController
		include CacheConfig
		respond_to :json

		def index
			name_params = params[:name]
			type_params = params[:type]

			if !name_params && !type_params
				@sources_list = Source.order(source_type: :desc, name: :asc).map { |source| { name: source.name, acronym: source.acronym, type: source.source_type }}
				#all_source_data = Source.all_sources_data
				#@sources_list = all_source_data[0][:sources]
			end

			if name_params != 'All'
				@sources = Source.where(name: name_params).empty? ? Source.where(acronym: name_params) : Source.where(name: name_params) 
			end

			if type_params
				@sources = Source.where(source_type: type_params)
			end

		end

	end

end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController

	def index
		@sources = Source.all
		#@national = Source.where(source_type: 'national') #.joins(:articles).includes(:articles).order('pub_date desc')
		#@blogs = Source.where(source_type: 'blogs') #.joins(:articles).includes(:articles).order('pub_date desc')
		#@international = Source.where(source_type: 'international') #.joins(:articles).includes(:articles).order('pub_date desc')
	end

	def new
		@source = Source.new
		@source.feeds.build
	end

	def create
		@source = Source.new(source_params)

		if @source.save
			redirect_to sources_path
		else
			render 'new'
		end

	end

	def show
		# @source = Source.includes(:feeds => :articles).find(params[:id])
		@source = Source.find(params[:id])
	end

	def edit
		@source = Source.find(params[:id])
	end

	def update
		@source = Source.find(params[:id])

		if @source.update(source_params)
			redirect_to sources_path
		else
			render 'edit'
		end
	end

	def destroy
		@source = Source.find(params[:id])
		@source.destroy

		redirect_to sources_path
	end

	private
		def source_params
			params.require(:source).permit(:name, :acronym, :url, :source_type, feeds_attributes: [:id, :name, :url, :source_id, :_destroy])
		end

end

app/helpers/sources_helper.rb
module SourcesHelper
  def cache_key_for_sources
    count = Source.count
    "sources/all-#{count}"
  end
end

app/views/sources/edit.html.erb
<h1>Editar Fonte</h1>

<%= render 'partials/form' %>

app/views/sources/index.html.erb
<h1>Fontes</h1>

<%= render 'partials/flash' %>

<p><%= link_to 'Adicionar fonte', new_source_path %></p>

<% cache(cache_key_for_sources, expires_in: 30.minutes) do %>
  <% @sources.pluck(:source_type).uniq.each do |source_type| %>
    <h3><%= source_type %></h3>
    <%= render partial: 'partials/sources_table', locals: {sources: @sources.where(source_type: source_type)} %>
  <% end %>
<% end %>

app/views/sources/new.html.erb
<h1>Nova Fonte</h1>

<%= render 'partials/form' %>

app/views/sources/show.html.erb
<h1><%= @source.name %></h1>

<%= render 'partials/flash' %>

<%= link_to 'Editar fonte', edit_source_path %>

<p>URL: <%= link_to @source.url, @source.url %></p>

<h2>Feeds</h2>

<% @source.feeds.each do |feed| %>
	<h4><%= feed.name %></h4> 
	<p><%= link_to feed.url, feed.url %> | <%= feed.articles.size %> artigos | Última recolha em <%= feed.last_crawled %></p>
	<table class="full-width tablesorter">
		<thead>
			<tr>
				<th>Título</th>
				<th>Publicada</th>
				<th>Recolhida</th>
				<th>Twitter</th>
				<th>Facebook</th>
				<th>Tópicos</th>
				<th>Acções</th>
			</tr>			
		</thead>
		<tbody>
			<% feed.articles.limit(10).each do |article| %>
				<tr>
					<td>

	          <%= link_to article.title, article.url %>
	        </td>
					<td><%= article.pub_date %></td>
					<td><%= article.created_at.in_time_zone('Lisbon') %></td>
					<td><%= article.twitter_shares.to_i %></td>
					<td><%= article.facebook_shares.to_i %></td>
					<td><%# article.cats.map(&:name).join(', ') %></td>
					<td><%= link_to 'Apagar', article_path(article),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
				</tr>
			<% end %>
		</tbody>
	</table>
<% end %>