config/routes.rb
Rails.application.routes.draw do

  resources :sources
  resources :articles

  namespace :api, defaults: { format: 'json' } do
    get 'sources' => 'sources#index'
    get 'items' => 'items#index'
    get 'feeds' => 'feeds#index'
    get 'totals' => 'totals#index'
    get 'pf' => 'totals#photo_finish'
    get 'wordcount' => 'totals#word_count'
    get 'stats' => 'stats#index'
    get 'places' => 'places#index'
  end

  get 'articles/duplicates' => 'articles#show'

  root 'sources#index'

end

app/views/partials/_flash.html.erb
<% if flash[:notice] %>
	<div class="success">
		<%= flash[:notice] %>
	</div>
<% end %>

app/views/partials/_form.html.erb
<% if @source.errors.any? %>
<div class="error">
	<ul>
  <% @source.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  <ul>
</div>
<% end %>

<%= nested_form_for @source do |f| %>
	
	<p>
		<%= f.label :source_type, 'Tipo de fonte' %>
		<%= select(:source, :source_type, [['Nacional', 'national'], ['Blog', 'blogs'], ['Internacional', 'international'], ['Arquivo', 'archive'], ['Media Brasileiros', 'br_media'], ['Investigação', 'research']]) %>
	</p>

	<p>
		<%= f.label :name, 'Nome' %>
		<%= f.text_field :name %>
	</p>

	<p>
		<%= f.label :acronym, 'Acrónimo' %>
		<%= f.text_field :acronym %>
	</p>

	<p>
		<%= f.label :url, 'URL' %>
		<%= f.text_field :url %>
	</p>

	<h2>Feeds</h2>

	<%= f.fields_for :feeds do |feeds_form| %>
		<p>
			<%= feeds_form.label :name, 'Nome' %>
			<%= feeds_form.text_field :name %>
		</p>
		
		<p>
			<%= feeds_form.label :url, 'URL' %>
			<%= feeds_form.text_field :url %>
		</p>

		<p>
			<%= feeds_form.link_to_remove "Remover feed" %>
		</p>

	<% end %>

	<p><%= f.link_to_add "Adicionar feed", :feeds %></p>

	<p>
		<%= f.submit 'Guardar fonte' %>
	</p>

<% end %>

<%= link_to 'Voltar', sources_path %>

app/views/partials/_sources_table.html.erb
<table class="tablesorter full-width">
	<thead>
		<tr>
			<th>Nome</th>
			<th>Feeds</th>
			<th>Artigos</th>
			<th>Twitter</th>
			<th>Facebook</th>
			<th>Última publicação</th>
			<th>Estado</th>
			<th>Acções</th>
		</tr>
	</thead>
	<tbody>
		<% sources.each do |source| %>
			<tr>
				<td>
          <%= link_to source.name, source %>
        </td>
				<td><%# source.feeds.size %></td>
				<td><%# source.articles.size %></td>
				<td><%# source.articles.pluck(:twitter_shares).compact.sum %></td>
				<td><%# source.articles.pluck(:facebook_shares).compact.sum %></td>
				<td><%# source.articles.first.pub_date || '' %></td>
				<td>
					<span class="circle <%# source.articles.order('pub_date DESC').first.pub_date < 2.days.ago ? "-alert" : "-ok" %>"></span>
				</td>
				<td><%= link_to 'Editar', edit_source_path(source) %> | <%= link_to 'Apagar', source_path(source),
                    method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
			</tr>
		<% end %>
	</tbody>
</table>